# Generated by Django 4.0.4 on 2022-04-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('salt', models.CharField(max_length=100)),
                ('md5', models.CharField(max_length=100)),
                ('sha1', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('ms', 'Ms')], max_length=2)),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.URLField(null=True)),
                ('medium', models.URLField(null=True)),
                ('thumbnail', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.TimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('female', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('cell', models.CharField(max_length=20, null=True)),
                ('nat', models.CharField(max_length=10)),
                ('dob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.dob')),
                ('id_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.id')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.location')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.login')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.name')),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.picture')),
                ('registered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.registered')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.timezone'),
        ),
    ]
